import type { Meta, StoryObj } from "@storybook/react";
import "../index.css";
import { ArtifactPanels } from "../components/ArtifactPanels";

const sampleDoc = {
  id: 1,
  title: "Demo Artifact",
  theme: "demo",
  doc_type: "text",
  summary: "Sample summary generated by the pipeline. Keep it concise and human-readable.",
  created_at: Date.now() / 1000,
};

const sampleArtifact = {
  task_id: 10,
  content_preview: "This is a preview of the OCR/text content captured by the worker.",
  metadata: { doc_type: "text", inferred_date: "2024-01-01", source: "storybook" },
  insights: { key: "value", risk: "low" },
  relevancy: { score: 82, rationale: "Matches coastal damage theme and mentions debris counts.", tags: ["coastal", "debris"] },
};

function PipelinePanelsPreview() {
  return (
    <div className="p-6 bg-slate-900 text-white space-y-4 max-w-5xl">
      <div>
        <p className="text-xs uppercase tracking-widest text-slate-400 mb-1">Document</p>
        <p className="text-sm text-slate-200 font-semibold">{sampleDoc.title}</p>
        <p className="text-xs text-slate-400">
          id #{sampleDoc.id} · {sampleDoc.theme} · {sampleDoc.doc_type}
        </p>
      </div>
      <ArtifactPanels
        summary={sampleDoc.summary}
        preview={sampleArtifact.content_preview}
        metadata={sampleArtifact.metadata}
        insights={sampleArtifact.insights}
        relevancy={sampleArtifact.relevancy}
        artifactJson={{ ...sampleArtifact, doc_id: sampleDoc.id }}
      />
    </div>
  );
}

const meta: Meta<typeof PipelinePanelsPreview> = {
  title: "Pipeline/ArtifactPanels",
  component: PipelinePanelsPreview,
};

export default meta;
type Story = StoryObj<typeof PipelinePanelsPreview>;

export const Default: Story = {};
