/**
 * Outreach Draft Generator
 * Auto-draft a neutral outreach message from geo context (heuristic; informational only)
 */
import { useState, useCallback } from 'react';
import { useDocsStore, useMapStore, useAppStore } from '../../store';
import { getConsultationContext, type ConsultationContext } from '../../utils/geoAnalysis';

interface LetterTemplate {
  subject: string;
  body: string;
  recipientName?: string;
  recipientOrg?: string;
}

export function ConsultationLetterGenerator() {
  const selectedId = useDocsStore((s) => s.selectedId);
  const docs = useDocsStore((s) => s.docs);
  const aoiGeojson = useMapStore((s) => s.aoiGeojson);
  const poiGeojson = useMapStore((s) => s.poiGeojson);
  const setBanner = useAppStore((s) => s.setBanner);

  const [selectedOfficeIndex, setSelectedOfficeIndex] = useState<number>(0);
  const [projectName, setProjectName] = useState('');
  const [projectDescription, setProjectDescription] = useState('');
  const [showPreview, setShowPreview] = useState(false);

  const selectedDoc = docs.find((d) => d.id === selectedId);
  
  // Get geo context
  let context: ConsultationContext | null = null;
  if (selectedDoc?.lat && selectedDoc?.lng) {
    context = getConsultationContext(selectedDoc.lat, selectedDoc.lng, aoiGeojson, poiGeojson);
  }

  const generateLetter = useCallback((): LetterTemplate | null => {
    if (!context || !selectedDoc) return null;

    const selectedOffice = context.nearbyOffices[selectedOfficeIndex];
    const today = new Date().toLocaleDateString('en-CA', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const territoriesText = context.territories.length > 0
      ? context.territories.map((t) => t.featureName).join(', ')
      : 'the surrounding area';

    const treatiesText = context.treaties.length > 0
      ? `Treaty layer overlaps: ${context.treaties.map((t) => t.featureName).join(', ')}.`
      : '';

    const subject = `Outreach: ${projectName || 'Project'} — location context (${territoriesText})`;

    const body = `${today}

${selectedOffice ? `${selectedOffice.name}\n` : 'Contact\n'}
${selectedOffice ? `Code: ${selectedOffice.code || 'N/A'}\n` : ''}

Subject: ${subject}

Hello,

We're working on ${projectName || 'a project'} and reviewing materials related to a location within ${territoriesText}.

${projectDescription ? `Context / request:\n${projectDescription}\n\n` : ''}Location Details:
- Coordinates: ${(selectedDoc.lat as number).toFixed(5)}, ${(selectedDoc.lng as number).toFixed(5)}
- Document: ${selectedDoc.title}

${treatiesText ? `\nMap layer overlaps:\n${treatiesText}\n` : ''}

Questions (optional):
1. Who is the right point of contact for this area?
2. Are there relevant sources, constraints, or considerations we should review?
3. What is your preferred communication channel and timeline?

Notes:
- This draft is generated from map overlays and may be incomplete.
- Please verify details with your own process and data sources.

Thanks,

[Your Name]
[Your Organization]
[Contact Information]

---
Generated by Pukaist Engine | Context signal: ${context.suggestedDepth.toUpperCase()}
`;

    return {
      subject,
      body,
      recipientName: selectedOffice?.name,
      recipientOrg: selectedOffice ? `Code: ${selectedOffice.code || 'N/A'}` : undefined,
    };
  }, [context, selectedDoc, selectedOfficeIndex, projectName, projectDescription]);

  const handleCopyLetter = useCallback(() => {
    const letter = generateLetter();
    if (letter) {
      void navigator.clipboard.writeText(`Subject: ${letter.subject}\n\n${letter.body}`);
      setBanner('Draft copied to clipboard');
    }
  }, [generateLetter, setBanner]);

  const handleDownloadLetter = useCallback(() => {
    const letter = generateLetter();
    if (letter) {
      const blob = new Blob([`Subject: ${letter.subject}\n\n${letter.body}`], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `outreach-draft-${Date.now()}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setBanner('Draft downloaded');
    }
  }, [generateLetter, setBanner]);

  if (!selectedDoc) {
    return (
      <div className="text-center py-4">
        <p className="text-sm text-slate-400">Select a document to draft an outreach message</p>
      </div>
    );
  }

  if (!context) {
    return (
      <div className="text-center py-4">
        <p className="text-sm text-slate-400">
          📍 Assign coordinates to this document first
        </p>
      </div>
    );
  }

  const letter = generateLetter();

  return (
    <div className="space-y-4">
      {/* Recipient Selection */}
      {context.nearbyOffices.length > 0 && (
        <div>
          <label className="text-xs text-slate-400 block mb-2">Recipient (nearby office/POI)</label>
          <select
            value={selectedOfficeIndex}
            onChange={(e) => setSelectedOfficeIndex(Number(e.target.value))}
            className="w-full bg-white/10 text-white text-sm px-3 py-2 rounded-lg border border-white/10"
          >
            {context.nearbyOffices.map((office, i) => (
              <option key={i} value={i}>
                {office.name} ({office.distance.toFixed(1)} km)
              </option>
            ))}
          </select>
        </div>
      )}

      {/* Project Details */}
      <div>
        <label className="text-xs text-slate-400 block mb-1">Project Name</label>
        <input
          type="text"
          value={projectName}
          onChange={(e) => setProjectName(e.target.value)}
          placeholder="e.g., Highway Expansion Phase 2"
          className="w-full bg-white/10 text-white text-sm px-3 py-2 rounded-lg border border-white/10"
        />
      </div>

      <div>
        <label className="text-xs text-slate-400 block mb-1">Context / Request (optional)</label>
        <textarea
          value={projectDescription}
          onChange={(e) => setProjectDescription(e.target.value)}
          placeholder="Brief context and what you’re asking for..."
          rows={3}
          className="w-full bg-white/10 text-white text-sm px-3 py-2 rounded-lg border border-white/10 resize-none"
        />
      </div>

      {/* Context Summary */}
      <div className="p-3 bg-slate-800/50 border border-white/10 rounded-lg">
        <p className="text-xs text-slate-400 mb-2">Auto-detected context:</p>
        <div className="space-y-1 text-xs">
          <p className="text-white">
            <span className={`
              ${context.suggestedDepth === 'high' ? 'text-red-400' : ''}
              ${context.suggestedDepth === 'medium' ? 'text-amber-400' : ''}
              ${context.suggestedDepth === 'low' ? 'text-green-400' : ''}
            `}>
              ● {context.suggestedDepth.toUpperCase()}
            </span> context signal
          </p>
          {context.territories.length > 0 && (
            <p className="text-slate-300">
              🏔️ {context.territories.map((t) => t.featureName).join(', ')}
            </p>
          )}
          {context.treaties.length > 0 && (
            <p className="text-slate-300">
              📜 {context.treaties.map((t) => t.featureName).join(', ')}
            </p>
          )}
        </div>
      </div>

      {/* Preview Toggle */}
      <button
        type="button"
        onClick={() => setShowPreview(!showPreview)}
        className="w-full py-2 text-sm bg-white/10 hover:bg-white/20 text-white rounded-lg"
      >
        {showPreview ? '▲ Hide Preview' : '▼ Show Draft Preview'}
      </button>

      {/* Letter Preview */}
      {showPreview && letter && (
        <div className="p-3 bg-slate-900 border border-white/10 rounded-lg max-h-64 overflow-y-auto">
          <pre className="text-xs text-slate-300 whitespace-pre-wrap font-mono">
            {letter.body}
          </pre>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-2">
        <button
          type="button"
          onClick={handleCopyLetter}
          className="flex-1 py-2 text-sm bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg flex items-center justify-center gap-2"
        >
          📋 Copy Draft
        </button>
        <button
          type="button"
          onClick={handleDownloadLetter}
          className="flex-1 py-2 text-sm bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg flex items-center justify-center gap-2"
        >
          💾 Download
        </button>
      </div>
    </div>
  );
}
